[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = +<main.cpp> -<bt_a2dp_sink.cpp>

lib_deps =
  adafruit/Adafruit AHTX0
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit GFX Library
  majicdesigns/MD_MAX72XX

[env:bluetooth_speaker]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_src_filter = +<bt_a2dp_sink.cpp> -<main.cpp>

lib_deps =
  https://github.com/pschatzmann/ESP32-A2DP
